### ISSUE TITLE
some small bugs

### ISSUE THREAD

**Issue by rahmanshaber** [marcusbritanicus/NewBreeze#22]
1.properties has no close button in window bar or in ui.
2.no setting button.
3.no way or button to go in super start
4.trash widow has no close button in window bar or in ui.
5.path and what is it showing dose not similer 
![ss](https://user-images.githubusercontent.com/30831735/36655179-42635f60-1aeb-11e8-9b24-fd32f48d2f07.png)
here path bar showing application but actual path is root.
6.prosess manager dose not show anything
![op](https://user-images.githubusercontent.com/30831735/36655244-a22a2e10-1aeb-11e8-9a66-6f31623bb369.png)
7.device dose not show all the drives.
![a](https://user-images.githubusercontent.com/30831735/36655301-09c3b35c-1aec-11e8-8049-87cd6234f4c3.png)
8.no way to bookmark.
9.no option to open terminal in current folder.

i used appimage and found this bug.
thanks for the appimage.

**Comment by marcusbritanicus** [comment]
1. The absence of close button was an old relic. Being accustomed to using keyboard more than mouse, I never noticed that. I'll fix that in the next commit.
2. Settings, as in most other cases, is opened by shortcuts. I am working on adding a slim menu for this inaccessible things. For now, shortcut: `Ctrl+Shift+S`
3. If Special location setting is enabled and set to SuperStart, you can access SuperStart by pressing `Alt+Shift+Home`
4. Same as 1. Press `Escape` to close it (for now).
5. I have not faced that problem. Could you tell me what sequence of steps causes that bug? I will fix it as soon as possible.
6. Process manager does not show anything, because there is nothing happening. If you copy/move/delete, you'll start seeing the processes there. The idea was to enable pausing of long operations like copy/move of large/large number of files without showing a jarring dialog.
7. DevicesView. I can see that Storage and FileSystem being mounted. What is the drive `Fast`? Is it mounted? It will show up in the devices list only if its mounted. Even after mounting, if it does not show up, then please show me the output of `df -h` I will be able to resolve that issue.
8. Bookmarking is `Ctrl+D`. Select the folder(s) you can to bookmark and press `Ctrl+D`.
On the other hand if you want to put them to SuperStart, press `Ctrl+U`. You can put both files and folders in SuperStart unlike in bookmarks.
9. Press `F4` to open terminal in current folder. If you want an inline terminal, press `Shift+F4`. Opening a terminal was always a part of NewBreeze. Inline terminal was introduced a few releases later at v1.1.6

**Comment by rahmanshaber** [comment]
1.please do not add any menu bar.wast of space .instead go , how gnome put there menu in a button .
![dd](https://user-images.githubusercontent.com/30831735/36667615-a803c166-1b18-11e8-992a-25656de782e8.png)

please no menubar. i have to use raspberrypi in a small screen .wasting space is not a choice for me.

2.Special location setting is enabled and set to SuperStart and clicked home button bettwen back and forward program crash all time. there is no shortcut for supperstart .

3. here is the sequence  for the wrong path .goto application >>then click adress bar>> change the path to root .here is the pic of the adress bar button.
![aa](https://user-images.githubusercontent.com/30831735/36667848-857fe02e-1b19-11e8-8259-356ac22ba522.png)
 
4.if ther is no prosess the write an text within the dialog as there is no prosess .

**Comment by marcusbritanicus** [comment]
Most of these issues are fixed. Menu is yet to be implemented.

**Comment by marcusbritanicus** [comment]
I have enabled addition/choice of terminals in the settings.

**Comment by rahmanshaber** [comment]
thanks.waiting for final release .

**Comment by marcusbritanicus** [comment]
NewBreeze has a menu now. You can test and play around with it. And report bugs!!
