### ISSUE TITLE
can't compile/install

### ISSUE THREAD

**Issue by dkebler** [marcusbritanicus/NewBreeze#27]
Running xenial.

These packeages are not even available in xenail I have the rest installed (all qt 5 stuff)
qtwebkit5-dev
QtWebEngine Qt 5.5 onwards (qtwebengine5-dev)
QScintilla (libqt5scintilla2-dev, libqscintilla2-qt5-dev)

compiles with this error 
```
cd Default/ && ( test -e Makefile || /usr/lib/x86_64-linux-gnu/qt5/bin/qmake /home/david/AllData/hacking/NewBreeze/plugins/Default/Default.pro -o Makefile ) && make -f Makefile 
Project ERROR: Unknown module(s) in QT: webengine webenginewidgets
Makefile:70: recipe for target 'sub-Default-make_first' failed
make[1]: *** [sub-Default-make_first] Error 3
make[1]: Leaving directory '/home/david/AllData/hacking/NewBreeze/plugins'
Makefile:94: recipe for target 'sub-plugins-make_first' failed
make: *** [sub-plugins-make_first] Error 2
```

 I tried to compile months ago unsuccessfully but just came back to see if you had done more work.  So yea but still having issues.   Would love to evaluate your efforts but can't get a binary installed.  What would be way cool is an ubuntu LTS build ppa (xenial).     If not then consider a nice bash script to check and install all dependencies.

**Comment by marcusbritanicus** [comment]
I'm glad you're interesetd in NewBreeze.

First thing, webengine and qscintilla are required only for plugins. So the application itself doesn't require it. To use it without plugins enter the common folder, and give the command: `sudo make install` and then enter the app folder and give the same command. This installs the `libnewbreeze-common.so` and `newbreeze3` in `/usr/lib/newbreeze` and `/usr/bin/`. You can now use NewBreeze.

Plugins is an issue. Well if you can give the list of package names that are available in both trusty and xenial, I'll write a separate `.pro` file of ubuntu. That would solve half the problems with all these packages. The current one will be used on other updated systems.

I would also suggest you to add ppa for qt5.9 by [Stephan Binner](https://launchpad.net/~beineri). This will give you Qt 5.5 and above for trusty and xenial. 

`libqt5scintilla2-dev` is available in trusty. Install it. In case you're using the ppa, then you'll have to give this command after installing qscintilla: `sudo mkdir -p /usr/include/x86_64-linux-gnu/qt5/ ; sudo ln -s /usr/include/qt5/Qsci /usr/include/x86_64-linux-gnu/qt5/` After that I believe you can compile with ease. 

Do let me know what you plan to do. I would have suggested you to use the deb files of alpha release, but a lot has changed since then. I'll be making a release soon, I'll see if I can make ubuntu-trusty, ubuntu-xenial debs along with an AppImage.

**Comment by rahmanshaber** [comment]
i think he is talking a ppa of Newbreeze for ubuntu 16.04LTS.

**Comment by marcusbritanicus** [comment]
I had tried once, long ago. Got fed up with it and deleted it. I really find Ubuntu tedious. If one of you is ready to create and manage the PPA, you have full support... 😀😉

**Comment by dkebler** [comment]
Probably going to wait on a new deb file (although I vaguely remember that not working before) but if I attempt suggestions above I'll let you know if that works.  Will add that ppa though as now and then compile other qt5 apps.   The AppImage binaries usually work for me so will try that when available.

Maybe there are better base distros than debian/ubuntu but it's the one I know and use and is likely the most installed for those wanting your file manager (i.e. linux mint).  So guess you are stuck making it compile there if you want any user base.  More than happy to help you figure out the least painful approach.  Would even set up a ppa if we can make builds pass faithfully.    I'm kinda tired of nemo and nautilus and they are both basically dead projects so looking for one that is actively maintained and will accept plugins and have easy customization (e.g.  context menus).   Thx

**Comment by marcusbritanicus** [comment]
Sadly I have not yet found sufficient time to try packaging in Ubuntu LTS. If and when I get time I will commit a fix. For now, this issue will continue to live in [GitLab](https://gitlab.com/marcusbritanicus/NewBreeze/issues/27)

**Comment by marcusbritanicus** [comment]
Sadly I have not yet found sufficient time to try packaging in Ubuntu LTS. If and when I get time I will commit a fix. For now, this issue will continue to live in [GitLab](https://gitlab.com/marcusbritanicus/NewBreeze/issues/27)

**Comment by marcusbritanicus** [comment]
I have [uploaded](https://gitlab.com/marcusbritanicus/NewBreeze/commit/f178ef6362afc12f63dc59fe0144bd72ab3dac71) a fix for Xenial. I am not very sure if it will work properly. I will be grateful if you can check it out. I have made the fixes based on my compilation issues while testing on Linux Mint 18.3 Sylvia from osboxes.org

**Comment by FabioLolix** [comment]
@marcusbritanicus I'm compiling and packaging this on Manjaro.

Which dependecies are mandatory and which are optional to run newbreeze?

for example djvulibre (libdjvulibre-dev) don't seem a mandatory one for the run

**Comment by marcusbritanicus** [comment]
libdjvulibre-dev is used for previewing the djvu files. Its not "mandatory" if you do not want the `Default` plugin or, if you're ready to disable a part of the `Default` plugin. Similarly, vlc, ffmpegthumbnailer, qscintilla, poppler, qtwebkit /qtwebengine are all required for plugins. Since NewBreeze can run without any plugins, these would be called "not mandatory".

The following are the mandatory packages for NewBreeze:

- Qt4/Qt5 (libqt4-dev, libqt4-dev-bin, qtbase5-dev, qtbase5-dev-tools)
- zlib (zlib1g-dev)
- liblzma (liblzma-dev)
- libbzip2 (libbz2-dev)
- libarchive (libarchive-dev)
- xdg-utils (xdg-utils)
- encfs

Again the package `encfs` is required for NewBreeze Vault (Inbuilt file/folder encryption support). Though you can run NewBreeze without installing `encfs` package, if you try encrypting folders, you'll fail to do so.

**Comment by marcusbritanicus** [comment]
@dkebler I have fixed up the sources, so that NB3 more or less compiles in Ubuntu 14.04. There are still several small issues which need fixing. But, for the time being I have provided an [AppImage](https://sourceforge.net/projects/newbreeze/files/v3-rc5/NewBreeze-x86_64.AppImage/download). It was compiled on Ubutnu 14.04 LTS, with updated native repos, 64 bit.
