### ISSUE TITLE
some issues 

### ISSUE THREAD

**Issue by rahmanshaber** [marcusbritanicus/NewBreeze#29]
1.in trash
![q1](https://user-images.githubusercontent.com/30831735/39818001-99182598-53c1-11e8-8cc8-6e2123eb24bd.png)

2.no icon on first start .
![q2](https://user-images.githubusercontent.com/30831735/39818911-dbe08648-53c3-11e8-8733-4cfb6fc0358d.png)

3.search button is not works properly.it dose not hid after clicking it.
![q3](https://user-images.githubusercontent.com/30831735/39819229-c1934f72-53c4-11e8-98d0-3539cd443267.png)

4.is mounting yet not supported? if yes see this pic.
![q4](https://user-images.githubusercontent.com/30831735/39819402-2d712372-53c5-11e8-9587-ce0ef4c3d4a0.png)

5.here is a random crash report.after crash>>build again>>clicking right button on any file crash the app.same output.
![q5](https://user-images.githubusercontent.com/30831735/39819569-96d18ee2-53c5-11e8-9209-34eda26732ba.png)

6.opening big folder ,like "/lib/" is slow and freeze the app for a moment.

7.no way to turn off the group in view.

8.terminal not found.
![q6](https://user-images.githubusercontent.com/30831735/39820237-2ae4a2da-53c7-11e8-9e4a-d6ab05ef6605.png)

8.no folder (like picture,home,downloads) in supperstart?

9.found no way to booknmark.

**Comment by marcusbritanicus** [comment]
1. I am not sure why NBTrashView does not render properly. I am able to view the Trash properly. I will look into it.
2. Which desktop environment are you using? Currently, I can search for icon theme of only
KDE, XFCE, GNOME, Razor, LXDE, OpenBox, TWM. If its something else, you'll have to set the icon theme manually.
3. I'll fix the search button in the next commit.
4. I'm not doing auto-mounting as of now. 
5. The crash happens when the default terminal is Inbuilt. Change the terminal and then there is no crash. I'll fix it in the next issue.
6. That is obvious. It has to load a lot of folders. There is nothing I can do about it as of now.
7. What do you mean turn off the group in view? If you want to disable sorting of files into groups, go to Settings (Ctrl+Shift+S) > General > □ Group files and folders by default. 
Uncheck the option. If it already is unchecked, check it once and then uncheck it.
8. SuperStart contains nothing by default. It's up to you to add files and folders to it. You'll find the option in the context menu.
9. Again, the option to add bookmarks is in the context menu.

**Comment by rahmanshaber** [comment]
1. ok
2.i am in xfce(manjaro). yes i can see all the icon pack.but when i select one it dose not automaticaly shows up as the main icon pack in the view . i also restarted the app but no change.after copule of restart then icons are showing up.
3. ok.
4. i am not talking about automount . i am telling that all my drives are not showing up in that list.they should't be??
5.did not understood.
6.make a progress bar or a little "loading animation gif " to show it is working. now it looks like it freeze the app ,so every time it freeze it can't click any button within the app. so at that time every one will close the app from process.
7.did what u told .but no changes . also "show in groups" button in menu not working.
8.right clicking on any file or folder crash the app. see the crash pic from first post.(number 5)
9. same , context menu crash the app.

happy fixing.

**Comment by marcusbritanicus** [comment]
As for drives (point no. 4), the drive 'Fast' is not mounted. If it's not mounted, then it won't show up. Only mounted drives/disks/partitions/devices show in the side panel.

**Comment by marcusbritanicus** [comment]
As for the context menu crashing, that's an internal bug. To avoid the crash, go to settings. In the terminal section, choose any other terminal that shows up and click on the default button. After that the context menu will work.

**Comment by marcusbritanicus** [comment]
Do check it out now. I have fixed most bugs. Unmounted drives will still not show up. Inbuilt terminal now works fine without causing crashes. I'll rewrite NBTrashView (It has been long pending) and push a commit sometime later.

**Comment by rahmanshaber** [comment]
trash is not fixed yet.
and show in group in menu is for what ? it dose not do any thing.
and any option to hide the bottom detail bar?

**Comment by marcusbritanicus** [comment]
1. Trash View is fixed now.
2. I am able to confirm that Show in Groups check box is not working. I'll fix it.
3. Bottom InfoBar cannot be hidden independently. I'll add an option later perhaps.
4. Did you install the app using `sudo make install`? If you do not want to install, then set the plugin paths in Settings (`Settings > Plugins > Add Path`)
5. Settings are applied immediately. 
6. You can see the copy/move progress in the address bar.

**Comment by marcusbritanicus** [comment]
Show in groups is now fixed.

**Comment by marcusbritanicus** [comment]
This issue has now been migrated to [GitLab](https://gitlab.com/marcusbritanicus/NewBreeze/issues/29)
